version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - flask_background

  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      - flask_background

  worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
    networks:
      - flask_background


networks:
  flask_background:
    driver: bridge
  